name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  GO_VERSION: '1.24'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/ingredients-balancer

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Check code formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted. Please run 'go fmt ./...'"
            gofmt -d .
            exit 1
          fi

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Gosec Security Scanner
        uses: securecodewarrior/github-action-gosec@master
        with:
          args: '-fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Run Nancy vulnerability scan
        run: |
          go install github.com/sonatypecommunity/nancy@latest
          go list -json -deps ./... | nancy sleuth

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23', '1.24']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: |
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./internal/... ./pkg/...

      - name: Test ingredient balancer operations
        run: |
          echo "Testing ingredient balancing logic..."
          go test -v -race ./pkg/application/
          echo "Testing gRPC ingredients balancer service..."
          go test -v -race ./pkg/infrastructure/grpc/

      - name: Test observability components
        run: |
          echo "Testing logging with tracing integration..."
          go test -v -race ./internal/infrastructure/logging/
          echo "Testing distributed tracing..."
          go test -v -race ./internal/infrastructure/tracing/

      - name: Generate coverage report
        if: matrix.go-version == env.GO_VERSION
        run: |
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage to Codecov
        if: matrix.go-version == env.GO_VERSION
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: ingredients-balancer-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage artifacts
        if: matrix.go-version == env.GO_VERSION
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint-and-format, unit-tests]
    
    services:
      jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
          - 16686:16686
          - 14268:14268
          - 4317:4317
          - 4318:4318
        env:
          COLLECTOR_OTLP_ENABLED: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: go mod download

      - name: Wait for Jaeger
        run: |
          echo "Waiting for Jaeger OTLP endpoint..."
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:16686/

      - name: Run gRPC integration tests
        run: go test -v -race ./test/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          DOCKER_HOST: unix:///var/run/docker.sock
          JAEGER_ENDPOINT: http://localhost:14268/api/traces
          OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318

      - name: Test gRPC ingredients balancer service end-to-end
        run: |
          echo "Starting ingredients balancer service in background..."
          go run ./cmd/ &
          SERVICE_PID=$!
          
          echo "Waiting for service to start..."
          sleep 5
          
          echo "Testing gRPC ingredients balancer operations..."
          go test -v ./test/ingredients_balancer_integration_test.go
          
          echo "Stopping service..."
          kill $SERVICE_PID || true

      - name: Test ingredient validation workflows
        run: |
          echo "Testing ingredient percentage validation..."
          go test -v -run TestValidation ./pkg/...
          
          echo "Testing recipe balancing algorithms..."
          go test -v -run TestBalancing ./pkg/...

      - name: Test observability integration
        run: |
          echo "Testing distributed tracing with ingredient balancing operations..."
          go test -v ./internal/infrastructure/logging/ ./internal/infrastructure/tracing/

  build:
    name: Build & Container
    runs-on: ubuntu-latest
    needs: [security, unit-tests]
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build ingredients balancer binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-s -w -X main.version=${{ github.sha }}" \
            -o bin/ingredients-balancer ./cmd/

      - name: Test ingredients balancer binary
        run: |
          ./bin/ingredients-balancer --help || echo "Ingredients balancer binary built successfully"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

  benchmarks:
    name: Ingredient Balancing Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run ingredient balancing benchmarks
        run: |
          echo "Running ingredient balancing algorithm benchmarks..."
          go test -bench=BenchmarkIngredientBalancing -benchmem -count=3 ./pkg/... | tee benchmark.txt
          
          echo "Running percentage calculation benchmarks..."
          go test -bench=BenchmarkPercentageCalculation -benchmem -count=3 ./pkg/... | tee -a benchmark.txt
          
          echo "Running gRPC server benchmarks..."
          go test -bench=BenchmarkGRPC -benchmem -count=3 ./test/... | tee -a benchmark.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: ingredients-balancer-benchmark-results
          path: benchmark.txt

  recipe-validation:
    name: Recipe Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test recipe validation rules
        run: |
          echo "Testing recipe percentage validation..."
          go test -v -run TestRecipeValidation ./pkg/...
          
          echo "Testing ingredient ratio calculations..."
          go test -v -run TestIngredientRatio ./pkg/...
          
          echo "Testing edge cases for ingredient balancing..."
          go test -v -run TestEdgeCases ./pkg/...

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [lint-and-format, security, unit-tests, integration-tests, build]
    if: always()
    
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.lint-and-format.result }}" != "success" ]]; then
            echo "Lint and format job failed"
            exit 1
          fi
          if [[ "${{ needs.security.result }}" != "success" ]]; then
            echo "Security job failed"
            exit 1
          fi
          if [[ "${{ needs.unit-tests.result }}" != "success" ]]; then
            echo "Unit tests job failed"
            exit 1
          fi
          if [[ "${{ needs.integration-tests.result }}" != "success" ]]; then
            echo "Integration tests job failed"
            exit 1
          fi
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "Build job failed"
            exit 1
          fi
          echo "All jobs completed successfully!" 